# Generated by Django 5.2 on 2025-04-24 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_last_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.TextField(blank=True, default='Not provided', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='contact_number',
            field=models.CharField(blank=True, default='027-339-6384', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(blank=True, default='2000-01-01', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='user@example.com', max_length=254, unique=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='full_name',
            field=models.CharField(default='Anonymous', max_length=255),
        ),
    ]
