# Generated by Django 5.2 on 2025-06-03 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_albumimage_image_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albumimage',
            name='image',
            field=models.ImageField(upload_to='portfolio_images/'),
        ),
    ]
