# Generated by Django 5.2 on 2025-06-04 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_albumimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albumimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio_images/'),
        ),
    ]
