# Generated by Django 5.2 on 2025-05-06 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_profile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='contact_number',
            field=models.CharField(blank=True, default='0273396384', max_length=10, null=True),
        ),
    ]
