# Generated by Django 5.2 on 2025-04-21 09:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browsetask', '0004_alter_post_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.RemoveField(
            model_name='post',
            name='text',
        ),
        migrations.AddField(
            model_name='post',
            name='address',
            field=models.CharField(default='No address provided', max_length=255),
        ),
        migrations.AddField(
            model_name='post',
            name='budget_option',
            field=models.CharField(default='Not sure', max_length=20),
        ),
        migrations.AddField(
            model_name='post',
            name='budget_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='task_images/'),
        ),
        migrations.AddField(
            model_name='post',
            name='task_details',
            field=models.TextField(default='No details provided'),
        ),
        migrations.AddField(
            model_name='post',
            name='task_title',
            field=models.CharField(default='Untitled Task', max_length=50),
        ),
        migrations.AddField(
            model_name='post',
            name='time_from',
            field=models.TimeField(default='00:00'),
        ),
        migrations.AddField(
            model_name='post',
            name='time_to',
            field=models.TimeField(default='23:59'),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
