# Generated by Django 5.2 on 2025-04-21 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browsetask', '0005_remove_post_author_remove_post_text_post_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
