# Generated by Django 5.2 on 2025-04-30 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browsetask', '0007_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('assigned', 'Assigned'), ('closed', 'Closed')], default='open', max_length=10),
        ),
    ]
