# Generated by Django 5.2 on 2025-05-08 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browsetask', '0010_post_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='full_name',
            field=models.CharField(default='Anonymous', max_length=100),
        ),
    ]
