# Generated by Django 5.2 on 2025-05-08 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('browsetask', '0011_offer_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='full_name',
        ),
    ]
