# Generated by Django 5.2 on 2025-05-13 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browsetask', '0012_remove_offer_full_name'),
        ('notifications', '0002_notification_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='task',
        ),
        migrations.AddField(
            model_name='notification',
            name='task_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='browsetask.post'),
        ),
    ]
