# Generated by Django 5.2 on 2025-05-13 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_remove_notification_task_notification_task_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='task_id',
            new_name='task',
        ),
    ]
