# Generated by Django 5.2 on 2025-05-22 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='new_message',
            field=models.BooleanField(default=False),
        ),
    ]
