# Generated by Django 5.2 on 2025-05-22 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_chatmessage_new_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='new_message',
            new_name='is_read',
        ),
    ]
